exports.dataparking = [
    {
        'number':'A1',
        'status':'available'
    },
    {
        'number':'A2',
        'status':'available'
    },
    {
        'number':'A3',
        'status':'available'
    },
    {
        'number':'A4',
        'status':'available'
    },
    {
        'number':'A5',
        'status':'available'
    },
    {
        'number':'A6',
        'status':'available'
    },
    {
        'number':'A7',
        'status':'available'
    },
    {
        'number':'A8',
        'status':'available'
    },
    {
        'number':'A9',
        'status':'available'
    },
    {
        'number':'A10',
        'status':'available'
    }
]